# Generated by Django 4.1 on 2022-08-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('actor', models.CharField(max_length=100)),
                ('poster_image', models.ImageField(upload_to='')),
                ('genres', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Thriller', 'Thriller')], max_length=50)),
            ],
        ),
    ]
